### ISSUE TITLE
[CLI] Make CLIs attach to existing instances of Runtime

### ISSUE THREAD

**Issue by levincent06** [pioneers/runtime#118]
When starting up each of the CLIs, they each spawn the corresponding instance of the Runtime component.
(Starting up net hander cli will `fork()`, then the child process will `exec()` a new net handler process.)

We would rather require that net handler is already started, then net handler CLI will simply feed commands to that process. This will prevent issues involving duplicate instances of Runtime, which may happen when the CLIs crash for whatever reason. This applies to all the main components of Runtime (shared memory, net handler, executor, and dev handler).

This will require changes to the `start()` functions in the clients. This will also affect the testing framework, as each individual test requires that specific components of Runtime are spawned at the start then cleaned up at the end.

**Comment by benliao1** [comment]
I think the only two CLIs that this would apply to are the shared memory UI and the net handler CLI because the executor one wouldn't normally be used to switch the student code when running on an existing instance of Runtime (you could do that with Dawn), and the dev_handler one doesn't work with an existing instance of Runtime (the CLI uses the client which creates virtual devices, not real USB devices).

With this smaller scope, making `shm_ui` and `net_handler_cli` be able to be attached to an existing instance of Runtime is actually not too bad. We can run them in a different mode by specifying a command line argument like `$> ./shm_ui attach` and `$> ./net_handler_cli attach`.
